# MAPS parent-data simulation with discrimination DIF.
# Uses longdat_maps_parent_discrim.csv generated by maps_parent_prep_discrim.R.

set.seed(20260513)

data_path <- "longdat_maps_parent_discrim.csv"
stan_path <- "maps_simulate_parent_discrim.stan"
out_dir <- "simulation_parent_discrim_output"
tmp_dir <- file.path(getwd(), "rstan_tmp")

dir.create(out_dir, showWarnings = FALSE)
dir.create(tmp_dir, showWarnings = FALSE)
Sys.setenv(TMPDIR = tmp_dir, TMP = tmp_dir, TEMP = tmp_dir)

if (!requireNamespace("cmdstanr", quietly = TRUE)) {
  stop("Package 'cmdstanr' is required.")
}
library(cmdstanr)

known_cmdstan_paths <- c(
  "C:/cmdstan/cmdstan-2.38.0",
  "C:/cmdstan-2.38.0/cmdstan-2.38.0"
)
current_cmdstan_path <- tryCatch(cmdstanr::cmdstan_path(), error = function(e) "")
if (!nzchar(current_cmdstan_path)) {
  found <- known_cmdstan_paths[dir.exists(known_cmdstan_paths)]
  if (length(found) == 0) {
    stop("CmdStan path is not set.")
  }
  cmdstanr::set_cmdstan_path(found[1])
}

message("Reading: ", data_path)
dat <- read.csv(data_path)
dat <- dat[order(dat$person_id, dat$time, dat$item), ]

predictor_names <- c("age_c", "korean_c", "income_c", "discrim_any")
missing_cols <- setdiff(
  c("person_id", "time", "item", "resp", predictor_names),
  names(dat)
)
if (length(missing_cols) > 0) {
  stop("Missing columns: ", paste(missing_cols, collapse = ", "))
}

complete_x <- complete.cases(dat[, predictor_names])
if (any(!complete_x)) {
  message("Dropping rows with missing DIF predictors: ", sum(!complete_x))
}
dat <- dat[complete_x, ]
dat$person_id <- as.integer(factor(dat$person_id))

Nobs <- nrow(dat)
P <- length(unique(dat$item))
Ni <- length(unique(dat$person_id))
D <- length(unique(dat$time))
K <- 5
Q <- length(predictor_names)

X_dif <- as.matrix(dat[, predictor_names])
time_value <- as.numeric(tapply(dat$time_c, dat$time, mean))

base <- list(
  log_loading = log(c(1.15, 1.00, 1.20, 0.95, 1.05, 1.15, 1.10, 0.90)),
  cutpoints = rbind(
    c(-2.10, -0.60, 0.85, 2.15),
    c(-1.80, -0.35, 1.00, 2.35),
    c(-1.95, -0.45, 0.95, 2.30),
    c(-1.65, -0.20, 1.15, 2.50),
    c(-1.85, -0.30, 1.05, 2.45),
    c(-1.70, -0.25, 1.10, 2.55),
    c(-2.00, -0.55, 0.90, 2.25),
    c(-1.55, -0.10, 1.25, 2.65)
  ),
  mu_intercept = -0.20,
  mu_slope = -0.07,
  intercept_sd = 0.85,
  slope_sd = 0.22,
  growth_corr = 0.20,
  occasion_sd = 0.35
)

zero_dif <- matrix(0, nrow = P, ncol = Q)
colnames(zero_dif) <- predictor_names

full_loading_dif <- zero_dif
full_threshold_dif <- zero_dif

# Columns: age_c, korean_c, income_c, discrim_any
# Positive threshold DIF means higher covariate values shift response thresholds upward.
# Negative threshold DIF means easier endorsement at the same latent trait level.
full_threshold_dif[2, "discrim_any"] <- -0.85
full_threshold_dif[6, "discrim_any"] <- -0.75
full_threshold_dif[7, "discrim_any"] <- -0.45
full_threshold_dif[4, "korean_c"] <- 0.35
full_threshold_dif[3, "korean_c"] <- 0.25
full_threshold_dif[4, "income_c"] <- 0.18
full_threshold_dif[3, "age_c"] <- 0.03

full_loading_dif[8, "korean_c"] <- -0.15
full_loading_dif[6, "discrim_any"] <- 0.12

make_stan_data <- function(condition) {
  loading_dif <- zero_dif
  threshold_dif <- zero_dif

  if (condition == "discrim_dif") {
    threshold_dif[, "discrim_any"] <- full_threshold_dif[, "discrim_any"]
    loading_dif[, "discrim_any"] <- full_loading_dif[, "discrim_any"]
  } else if (condition == "full_dif") {
    threshold_dif <- full_threshold_dif
    loading_dif <- full_loading_dif
  } else if (condition != "no_dif") {
    stop("Unknown condition: ", condition)
  }

  list(
    Nobs = Nobs,
    P = P,
    Ni = Ni,
    D = D,
    K = K,
    Q = Q,
    person = dat$person_id,
    item = dat$item,
    wave = dat$time,
    time_value = time_value,
    X_dif = X_dif,
    log_loading = base$log_loading,
    cutpoints = base$cutpoints,
    loading_dif = loading_dif,
    threshold_dif = threshold_dif,
    mu_intercept = base$mu_intercept,
    mu_slope = base$mu_slope,
    intercept_sd = base$intercept_sd,
    slope_sd = base$slope_sd,
    growth_corr = base$growth_corr,
    occasion_sd = base$occasion_sd
  )
}

message("Compiling: ", stan_path)
model <- cmdstanr::cmdstan_model(stan_path, dir = out_dir)

simulate_condition <- function(condition, seed) {
  message("Simulating: ", condition)
  fit <- model$sample(
    data = make_stan_data(condition),
    fixed_param = TRUE,
    chains = 1,
    parallel_chains = 1,
    iter_warmup = 0,
    iter_sampling = 1,
    seed = seed,
    refresh = 0,
    output_dir = out_dir
  )
  y <- as.integer(fit$draws(variables = "Y_sim", format = "draws_matrix")[1, ])
  out <- dat
  out$resp_observed <- out$resp
  out$resp <- y
  out$condition <- condition
  out
}

sim_no <- simulate_condition("no_dif", 20260513)
sim_disc <- simulate_condition("discrim_dif", 20260514)
sim_full <- simulate_condition("full_dif", 20260515)

write.csv(sim_no, file.path(out_dir, "longdat_parent_sim_no_dif.csv"), row.names = FALSE)
write.csv(sim_disc, file.path(out_dir, "longdat_parent_sim_discrim_dif.csv"), row.names = FALSE)
write.csv(sim_full, file.path(out_dir, "longdat_parent_sim_full_dif.csv"), row.names = FALSE)
write.csv(rbind(sim_no, sim_disc, sim_full),
          file.path(out_dir, "longdat_parent_sim_all_conditions.csv"),
          row.names = FALSE)

truth <- rbind(
  data.frame(type = "loading", item = rep(seq_len(P), each = Q),
             predictor = rep(predictor_names, times = P),
             value = as.vector(t(full_loading_dif))),
  data.frame(type = "threshold", item = rep(seq_len(P), each = Q),
             predictor = rep(predictor_names, times = P),
             value = as.vector(t(full_threshold_dif)))
)
truth$has_dif <- truth$value != 0
write.csv(truth, file.path(out_dir, "simulation_true_dif_parameters.csv"),
          row.names = FALSE)

observed <- dat
observed$condition <- "observed"
observed$resp_observed <- observed$resp
plot_dat <- rbind(
  observed[, names(sim_no)],
  sim_no,
  sim_disc,
  sim_full
)

overall <- do.call(rbind, lapply(split(plot_dat, plot_dat$condition), function(x) {
  data.frame(
    condition = x$condition[1],
    n = nrow(x),
    mean_resp = mean(x$resp),
    sd_resp = sd(x$resp),
    prop_high_4_5 = mean(x$resp >= 4),
    prop_discrim = mean(x$discrim_any == 1)
  )
}))
write.csv(overall, file.path(out_dir, "observed_vs_simulated_overall_summary.csv"),
          row.names = FALSE)

mean_by_wave <- aggregate(resp ~ condition + time, data = plot_dat, mean)
write.csv(mean_by_wave, file.path(out_dir, "observed_vs_simulated_mean_by_wave.csv"),
          row.names = FALSE)

mean_by_discrim <- aggregate(resp ~ condition + discrim_any + item, data = plot_dat, mean)
write.csv(mean_by_discrim, file.path(out_dir, "observed_vs_simulated_by_discrim_item.csv"),
          row.names = FALSE)

png(file.path(out_dir, "poster_observed_vs_simulated_discrim.png"),
    width = 2600, height = 1500, res = 220)
op <- par(mfrow = c(1, 2), mar = c(4.3, 4.3, 2.6, 1), oma = c(0, 0, 2, 0))

cols <- c(
  observed = "black",
  no_dif = "#D95F02",
  discrim_dif = "#1B9E77",
  full_dif = "#7570B3"
)
ltys <- c(observed = 1, no_dif = 3, discrim_dif = 2, full_dif = 4)

plot(NA, xlim = range(mean_by_wave$time), ylim = range(mean_by_wave$resp),
     xlab = "Wave", ylab = "Mean response",
     main = "Observed vs simulated trajectories", xaxt = "n")
axis(1, at = sort(unique(mean_by_wave$time)))
for (cond in names(cols)) {
  one <- mean_by_wave[mean_by_wave$condition == cond, ]
  lines(one$time, one$resp, type = "b", pch = 16, col = cols[cond],
        lty = ltys[cond], lwd = 2.4)
}
legend("topright", legend = c("Observed", "No DIF", "Discrimination DIF", "Full DIF"),
       col = cols, lty = ltys, pch = 16, lwd = 2.4, bty = "n", cex = 0.82)

disc_plot <- aggregate(resp ~ condition + discrim_any, data = plot_dat, mean)
disc_plot$group <- ifelse(disc_plot$discrim_any == 1, "Discrimination", "No discrimination")
bar_mat <- xtabs(resp ~ group + condition, data = disc_plot)
barplot(bar_mat[, names(cols)], beside = TRUE, col = c("#A6CEE3", "#FB9A99"),
        ylab = "Mean response", main = "Mean response by discrimination status",
        names.arg = c("Observed", "No DIF", "Disc DIF", "Full DIF"),
        ylim = c(0, max(bar_mat) * 1.18))
legend("topright", legend = rownames(bar_mat), fill = c("#A6CEE3", "#FB9A99"),
       bty = "n", cex = 0.82)

mtext("MAPS parent-data Stan simulation with discrimination DIF",
      outer = TRUE, cex = 1.15, font = 2)
par(op)
dev.off()

message("Done.")
message("Main outputs:")
message("  ", file.path(out_dir, "poster_observed_vs_simulated_discrim.png"))
message("  ", file.path(out_dir, "observed_vs_simulated_overall_summary.csv"))
message("  ", file.path(out_dir, "simulation_true_dif_parameters.csv"))
